---
name: Continuous Integration

on:
    pull_request:
    push:
        branches:
            - '*'
            - '*/*'
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
                  fetch-depth: 1

            - name: Run Docker container
              run: docker compose up -d

            - name: Build ROS Package
              run: |
                  source ./.env
                  docker exec "$CONTAINER_NAME" /bin/zsh -c "source /opt/ros/humble/setup.zsh && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-skip arise_slam_mid360 arise_slam_mid360_msgs livox_ros_driver2 receive_theta"
              shell: /usr/bin/bash -e {0}
